spring:
  profiles:
    active: usage_message  
  rabbitmq:
    host: localhost
    password: test
    username: test
    port: 5672


logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000

